apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
spec:
  minReadySeconds: 20
  selector:
    matchLabels:
      app: webapp
  replicas: 2
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: richardchesterwood/k8s-fleetman-webapp-angular:release0

---

apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: queue
spec:
  selector:
    matchLabels:
      app: queue
  replicas: 2
  template:
    metadata:
      labels:
        app: queue

    spec:
      containers:
      - name: queue
        image: richardchesterwood/k8s-fleetman-queue:release1
